
tasks:

# Install Salesforce CLI trough NPM
- name: 'Install Salesforce CLI'
  init: |
      npm install sfdx-cli --global
  command: |
      npm install @salesforce/cli --global
      sfdx --version
      sfdx autocomplete
      printf "eval $(sfdx autocomplete script bash)" >> ~/.bashrc; source ~/.bashrc

vscode:
  extensions:
    - salesforce.salesforcedx-vscode
    - salesforce.salesforcedx-vscode-expanded
