tasks:

# Now Install Salesforce CLI
- name: 'Install Salesforce CLI'
  init: |
      wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
      mkdir sfdx
      tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
      rm -r sfdx-linux-x64.tar.xz 
      ~/sfdx/bin/sfdx version